### ISSUE TITLE
Nesting of 100 is too deep

### ISSUE THREAD

**Issue by andreiaionitoaiesv** [allure-framework/allure-ruby#147]
So I saw this error when running my tests.

```
Nesting of 100 is too deep
/usr/local/bundle/gems/allure-ruby-commons-2.13.1/lib/allure_ruby_commons/model/jsonable.rb:17:in `to_json'
/usr/local/bundle/gems/allure-ruby-commons-2.13.1/lib/allure_ruby_commons/model/jsonable.rb:17:in `to_json'
/usr/local/bundle/gems/allure-ruby-commons-2.13.1/lib/allure_ruby_commons/file_writer.rb:17:in `write_test_result'
/usr/local/bundle/gems/allure-ruby-commons-2.13.1/lib/allure_ruby_commons/allure_lifecycle.rb:88:in `stop_test_case'
/usr/local/bundle/gems/allure-rspec-2.13.1/lib/allure_rspec/formatter.rb:55:in `example_finished'
/usr/local/bundle/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:201:in `block in notify'
/usr/local/bundle/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:200:in `each'
/usr/local/bundle/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:200:in `notify'
/usr/local/bundle/gems/rspec-core-3.8.2/lib/rspec/core/reporter.rb:126:in `example_finished'
/usr/local/bundle/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:492:in `record_finished'
/usr/local/bundle/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:484:in `finish'
/usr/local/bundle/gems/rspec-core-3.8.2/lib/rspec/core/example.rb:286:in `run'
```

On 2.13.1. 

I believe the issue is here. 
https://github.com/allure-framework/allure-ruby/blob/master/allure-ruby-commons/lib/allure_ruby_commons/model/jsonable.rb#L22

Can we add **max_nesting: false**  ?

**Comment by andrcuns** [comment]
Do you have any example to reliably reproduce this?
