### ISSUE TITLE
Allure and Codecov Encoding::UndefinedConversionError 

### ISSUE THREAD

**Issue by griou** [allure-framework/allure-ruby#174]
Hello, 

I have an error with codecov and allure, I don't know how to fix it, it does not happen every time.

``` _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _\`|/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                               Ruby-0.2.11
==> Circle CI detected
==> Appending file network
==> Gzipping contents
==> Uploading reports
Stopped processing SimpleCov as a previous error not related to SimpleCov has been detected
```

``` Failure/Error: super(options)
     
     Encoding::UndefinedConversionError:
       "\xE2" from ASCII-8BIT to UTF-8
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4/lib/active_support/core_ext/object/json.rb:38:in `to_json'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4/lib/active_support/core_ext/object/json.rb:38:in `to_json'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/allure-ruby-commons-2.13.6.3/lib/allure_ruby_commons/model/jsonable.rb:23:in `to_json'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4/lib/active_support/core_ext/object/json.rb:38:in `to_json'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4/lib/active_support/core_ext/object/json.rb:38:in `to_json'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/allure-ruby-commons-2.13.6.3/lib/allure_ruby_commons/model/jsonable.rb:23:in `to_json'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/json_pure-2.3.0/lib/json/common.rb:224:in `generate'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/json_pure-2.3.0/lib/json/common.rb:224:in `generate'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/allure-ruby-commons-2.13.6.3/lib/allure_ruby_commons/file_writer.rb:21:in `write_test_result'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/allure-ruby-commons-2.13.6.3/lib/allure_ruby_commons/allure_lifecycle.rb:100:in `stop_test_case'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/allure-rspec-2.13.6.3/lib/allure_rspec/formatter.rb:59:in `example_finished'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:209:in `block in notify'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:208:in `each'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:208:in `notify'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:134:in `example_finished'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:497:in `record_finished'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:480:in `finish'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example.rb:440:in `fail_with_exception'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:613:in `block in run'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:654:in `each'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:654:in `for_filtered_examples'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:658:in `block in for_filtered_examples'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:656:in `each'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:656:in `for_filtered_examples'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:613:in `rescue in run'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:609:in `run'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:607:in `block in run'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:607:in `map'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/example_group.rb:607:in `run'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:121:in `map'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/configuration.rb:2061:in `with_suite_hooks'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/reporter.rb:74:in `report'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:115:in `run_specs'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:89:in `run'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:71:in `run'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/lib/rspec/core/runner.rb:45:in `invoke'
     # /path_to_project/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.9.3/exe/rspec:4:in `<top (required)>'
     # /path_to_project/vendor/bundle/ruby/2.7.0/bin/rspec:23:in `load'
     # /path_to_project/vendor/bundle/ruby/2.7.0/bin/rspec:23:in `<top (required)>'
     # /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `load'
     # /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:63:in `kernel_load'
     # /usr/local/lib/ruby/2.7.0/bundler/cli/exec.rb:28:in `run'
     # /usr/local/lib/ruby/2.7.0/bundler/cli.rb:476:in `exec'
     # /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
     # /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
     # /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
     # /usr/local/lib/ruby/2.7.0/bundler/cli.rb:30:in `dispatch'
     # /usr/local/lib/ruby/2.7.0/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
     # /usr/local/lib/ruby/2.7.0/bundler/cli.rb:24:in `start'
     # /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:46:in `block in <top (required)>'
     # /usr/local/lib/ruby/2.7.0/bundler/friendly_errors.rb:123:in `with_friendly_errors'
     # /usr/local/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/libexec/bundle:34:in `<top (required)>'
     # /usr/local/bin/bundle:23:in `load'
     # /usr/local/bin/bundle:23:in `<main>'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
     # ------------------
     # --- Caused by: ---
     # Encoding::UndefinedConversionError:
     #   "\xE2" from ASCII-8BIT to UTF-8
     #   /path_to_project/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4/lib/active_support/core_ext/object/json.rb:38:in `to_json'
```

Do you have any hint to solve it ?

**Comment by andrcuns** [comment]
Hmm, don't really know what could cause this just by looking at stack trace. What seems strange, is it uses to_json from activesupport, which was not my intention and active_support is dependency of cucumber so it is rather strange it is used if you would use rspec adapter.

Unfortunately as usually it goes, it's hard for me to debug this further without being able to reproduce this issue. I might take a look and see if I can force using the default JSON implementation. Though it does seem the issue might lie in your tests which create some non UTF character which adapter tries to put in the json.

**Comment by andrcuns** [comment]
I released a new version which changes the way how json files are generated, there is a small chance it could help.

Other than that, [this](https://stackoverflow.com/questions/21639275/python-syntaxerror-non-ascii-character-xe2-in-file) post might help you figure out the issue, as I'm pretty sure it's due to having some invalid character in some of the files that allure is picking up.

**Comment by griou** [comment]
Thank you a lot for your response and the new release. I'll test it and let you know if it solved the issue!
