### ISSUE TITLE
Output override is not working in 2.13.10

### ISSUE THREAD

**Issue by karoisuzvards** [allure-framework/allure-ruby#276]
Hello dear acquaintance! 😄 

In `2.13.9` it was possible to override output folder:
somewhere in `cucumber.yml`:
```
<%=
allure_reporter = "--format AllureCucumber::CucumberFormatter --out tmp/#{ENV['ALLURE_RESULTS'] || 'cucumber'}"
%>
```
in `env.rb`:
```
# Allure
AllureCucumber.configure do |c|
  c.results_directory = "tmp/cucumber"
  ...
end
```
i.e. if `ALLURE_RESULTS` env var is set to `"hello"` then output would be written to `tmp/hello` folder

but for same configuration code  when using `2.13.10` output is written in `tmp/cucumber` 

of course its an easy fix but is not this considered a regression from configuration point of view ?  🐛

**Comment by andrcuns** [comment]
Definitely is, something got broken.

**Comment by andrcuns** [comment]
I did a quick test in this repo and can't seem to reproduce it: https://github.com/allure-examples/allure-cucumber-example.

```console
bundle exec cucumber --format AllureCucumber::CucumberFormatter --out strange-folder
Using the default profile...
Feature: Using Google

  @TMS_QA-123 @ISSUE_BUG-123
  Scenario Outline: Searching for a term # features/google.feature:4
    Given I am on                        # features/google.feature:6
      """
      google.com
      """
    When I enter "<search_term>"         # features/google.feature:10
    Then I should see results            # features/google.feature:11

    Examples:
      | search_term |
      | pizza       |
      expected to find visible css "[role=listbox]" but there were no matches. Also found "", which matched the selector but not all filters.  (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/google_steps.rb:12:in `nil'
      features/google.feature:14:11:in `I should see results'
      | banana      |
      expected to find visible css "[role=listbox]" but there were no matches. Also found "", which matched the selector but not all filters.  (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/google_steps.rb:12:in `nil'
      features/google.feature:15:11:in `I should see results'

  Scenario: Github page has icon  # features/google.feature:17
    Given I am on                 # features/step_definitions/google_steps.rb:3
      """
      github.com
      """
    Then I should see github icon # features/step_definitions/google_steps.rb:15

  Scenario: Gitlab page has icon  # features/google.feature:24
    Given I am on                 # features/step_definitions/google_steps.rb:3
      """
      gitlab.com
      """
    Then I should see gitlab icon # features/step_definitions/google_steps.rb:19

Failing Scenarios:
cucumber features/google.feature:14 # Scenario Outline: Searching for a term
cucumber features/google.feature:15 # Scenario Outline: Searching for a term

4 scenarios (2 failed, 2 passed)
10 steps (2 failed, 8 passed)
0m18.170s
┌──────────────────────────────────────────────────────────────────────────┐
│ Share your Cucumber Report with your team at https://reports.cucumber.io │
│                                                                          │
│ Command line option:    --publish                                        │
│ Environment variable:   CUCUMBER_PUBLISH_ENABLED=true                    │
│ cucumber.yml:           default: --publish                               │
│                                                                          │
│ More information at https://reports.cucumber.io/docs/cucumber-ruby       │
│                                                                          │
│ To disable this message, specify CUCUMBER_PUBLISH_QUIET=true or use the  │
│ --publish-quiet option. You can also add this to your cucumber.yml:      │
│ default: --publish-quiet                                                 │
└──────────────────────────────────────────────────────────────────────────┘

❯ ls strange-folder
3c2b51a0-9cfb-0139-b6e9-2cde48001122-container.json 3e668020-9cfb-0139-b6e9-2cde48001122-container.json 3fd6c460-9cfb-0139-b6e9-2cde48001122-container.json 46611d10-9cfb-0139-b6e9-2cde48001122-container.json
3c2b5650-9cfb-0139-b6e9-2cde48001122-result.json    3e6685c0-9cfb-0139-b6e9-2cde48001122-result.json    3fd6c900-9cfb-0139-b6e9-2cde48001122-result.json    46612300-9cfb-0139-b6e9-2cde48001122-result.json
3c324120-9cfb-0139-b6e9-2cde48001122-attachment.txt 3e66a430-9cfb-0139-b6e9-2cde48001122-attachment.txt 3fd6e8f0-9cfb-0139-b6e9-2cde48001122-attachment.txt 466149e0-9cfb-0139-b6e9-2cde48001122-attachment.txt
```

**Comment by karoisuzvards** [comment]
Seems that its ok if override from CLI, but when cucumber profiles is used - can reproduce: 

 https://github.com/allure-examples/allure-cucumber-example/pull/168

**Comment by karoisuzvards** [comment]
Same example works when using 2.13.9

```bash
➜  allure-cucumber-example git:(change-out-in-cucumber-yml) ✗ grep allure-cucumber Gemfile
gem 'allure-cucumber', '2.13.9'

➜  allure-cucumber-example git:(change-out-in-cucumber-yml) ✗ ls                          
Gemfile      Gemfile.lock README.md    config       features

➜  allure-cucumber-example git:(change-out-in-cucumber-yml) ✗ bundle exec cucumber
Using the default profile...
Feature: Using Google

<omitted for brevity>

➜  allure-cucumber-example git:(change-out-in-cucumber-yml) ✗ ls
Gemfile      Gemfile.lock README.md    config       features     report

➜  allure-cucumber-example git:(change-out-in-cucumber-yml) ✗ ls report
strange-folder
```

**Comment by andrcuns** [comment]
Should work now. No e2e tests so a 🐛 slipped by 😸
